import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1789917564488 implements MigrationInterface {
    name = 'InitSchema1789917564488'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // uuid_generate_v4() dùng làm default cho mọi PrimaryGeneratedColumn('uuid') — TypeORM tự
        // tạo extension này khi chạy synchronize, nhưng migration chạy độc lập nên khai báo rõ ràng
        // ở đây để không phụ thuộc hành vi ngầm của driver trên CSDL hosting thật (Supabase).
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TYPE "public"."cvs_type_enum" AS ENUM('template', 'upload')`);
        await queryRunner.query(`CREATE TABLE "cvs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidate_profile_id" uuid NOT NULL, "type" "public"."cvs_type_enum" NOT NULL DEFAULT 'template', "file_url" character varying, "original_file_name" character varying, "file_data" bytea, "file_mime_type" character varying, "external_link_url" character varying, "is_primary" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e7d8a4d55eb4e7a2e43bea8d83a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."company_users_type_enum" AS ENUM('main', 'sub')`);
        await queryRunner.query(`CREATE TABLE "company_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "user_id" uuid NOT NULL, "type" "public"."company_users_type_enum" NOT NULL DEFAULT 'sub', "permissions" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fcd31773e604355d8a473de888c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "service_packages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" character varying NOT NULL, "quantity" integer NOT NULL, "duration_days" integer NOT NULL, "price" bigint NOT NULL, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d602a30f23af1a0ecf7c8e994df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'success', 'failed')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "gateway" character varying NOT NULL, "transaction_code" character varying, "amount" bigint NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'issued', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "invoice_number" character varying, "vat_amount" bigint NOT NULL DEFAULT '0', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'draft', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ea83c3b911906a3578de2340fdf" UNIQUE ("order_id"), CONSTRAINT "REL_ea83c3b911906a3578de2340fd" UNIQUE ("order_id"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_payment_method_enum" AS ENUM('vnpay', 'momo', 'zalopay', 'vietqr', 'contract_vat')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'active', 'expired', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "service_package_id" uuid NOT NULL, "quantity" integer NOT NULL, "remaining" integer NOT NULL, "payment_method" "public"."orders_payment_method_enum" NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending', "activated_at" TIMESTAMP WITH TIME ZONE, "expires_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."companies_approval_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "companies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "tax_code" character varying NOT NULL, "size" character varying, "industry" character varying, "website" character varying, "approval_status" "public"."companies_approval_status_enum" NOT NULL DEFAULT 'pending', "legal_doc_url" character varying, "legal_doc_original_file_name" character varying, "legal_doc_external_link" character varying, "legal_doc_data" bytea, "legal_doc_mime_type" character varying, "is_featured_employer" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6c88910b191c8828840e4647a5e" UNIQUE ("tax_code"), CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b955c977390fc5903ea2519506" ON "companies"  ("approval_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2eb06ff133d04a6805a3fa4cea" ON "companies"  ("is_featured_employer") `);
        await queryRunner.query(`CREATE TYPE "public"."applications_status_enum" AS ENUM('new', 'reviewing', 'suitable', 'rejected', 'interview')`);
        await queryRunner.query(`CREATE TABLE "applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_posting_id" uuid NOT NULL, "cv_id" uuid NOT NULL, "status" "public"."applications_status_enum" NOT NULL DEFAULT 'new', "cover_letter" text, "rating" smallint, "folder" character varying, "deleted_at" TIMESTAMP, "applied_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_938c0a27255637bde919591888f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_770f0a8b0033dd04c3fcc55d69" ON "applications"  ("job_posting_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc56541877aa49408cdf38a735" ON "applications"  ("cv_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ee114cee92e995a9e75c05cfb" ON "applications"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d2b6efa58d11141449bc3a12de" ON "applications"  ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b9836f9e3cd74cfcb2c2da66d" ON "applications"  ("folder") `);
        await queryRunner.query(`CREATE INDEX "IDX_d134cbc7a07bded22846799771" ON "applications"  ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae4173257eebabee3db1cee885" ON "applications"  ("job_posting_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."job_postings_approval_status_enum" AS ENUM('draft', 'pending', 'approved', 'rejected', 'expired')`);
        await queryRunner.query(`CREATE TABLE "job_postings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "title" character varying NOT NULL, "industry" character varying, "location" character varying, "provinces" text, "district" character varying, "experience_level" character varying, "is_urgent" boolean NOT NULL DEFAULT false, "is_paused" boolean NOT NULL DEFAULT false, "salary_min" integer, "salary_max" integer, "employment_type" character varying, "level" character varying, "headcount" integer NOT NULL DEFAULT '1', "description" text, "requirements" text, "benefits" text, "banner_image_url" character varying, "banner_image_external_link" character varying, "deadline" date, "approval_status" "public"."job_postings_approval_status_enum" NOT NULL DEFAULT 'draft', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dda635ece382c8ad2d90a179182" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bd239aea48fdd78095c23e51e0" ON "job_postings"  ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c7584f5c38d2693d38c076cea5" ON "job_postings"  ("industry") `);
        await queryRunner.query(`CREATE INDEX "IDX_580ae81cb102623fd17eb424ac" ON "job_postings"  ("district") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1a959e31fc12e2fc21542e6c0" ON "job_postings"  ("experience_level") `);
        await queryRunner.query(`CREATE INDEX "IDX_b11b4640f95bb56b6bd3c2c04f" ON "job_postings"  ("employment_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_3adbc559e344968a1d216d9798" ON "job_postings"  ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_f82c7b577f57dd7c3ef5f79f08" ON "job_postings"  ("deadline") `);
        await queryRunner.query(`CREATE INDEX "IDX_68887787f572d94640efb1e595" ON "job_postings"  ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_5985a72c87165933e440392de3" ON "job_postings"  ("approval_status", "is_paused") `);
        await queryRunner.query(`CREATE TABLE "saved_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidate_profile_id" uuid NOT NULL, "job_posting_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1e106c66fc89f96addc57f71fb0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "blocked_companies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidate_profile_id" uuid NOT NULL, "company_id" uuid, "company_name_text" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c148f911798cc43d6236a4e5a99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "candidate_experiences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidate_profile_id" uuid NOT NULL, "position" character varying NOT NULL, "company_name" character varying, "start_date" date, "end_date" date, "is_current" boolean NOT NULL DEFAULT false, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7317b56ca8e5b5c5a69e7a58296" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "candidate_educations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidate_profile_id" uuid NOT NULL, "school_name" character varying, "degree" character varying, "major" character varying, "start_date" date, "end_date" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_926cb0760dd697b7b9a109adc6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "candidate_certificates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidate_profile_id" uuid NOT NULL, "name" character varying NOT NULL, "issuer" character varying, "issue_date" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bfc37d23929e3908924ab33ae3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."candidate_languages_level_enum" AS ENUM('native', 'excellent', 'good', 'fair', 'beginner')`);
        await queryRunner.query(`CREATE TABLE "candidate_languages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidate_profile_id" uuid NOT NULL, "language" character varying NOT NULL, "level" "public"."candidate_languages_level_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_34dd59c43dc6bea95a7b172a849" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."candidate_skills_level_enum" AS ENUM('beginner', 'intermediate', 'advanced', 'expert')`);
        await queryRunner.query(`CREATE TABLE "candidate_skills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidate_profile_id" uuid NOT NULL, "skill_name" character varying NOT NULL, "level" "public"."candidate_skills_level_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e1bb466425868a6a6169ee0ee8f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "candidate_achievements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidate_profile_id" uuid NOT NULL, "title" character varying NOT NULL, "description" text, "date" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6b8024fcb65798db1df004849b1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "candidate_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidate_profile_id" uuid NOT NULL, "title" character varying NOT NULL, "organization_name" character varying, "start_date" date, "end_date" date, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1ee970b6026814cf1f249e84d6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "candidate_references" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidate_profile_id" uuid NOT NULL, "full_name" character varying NOT NULL, "position" character varying, "company" character varying, "phone" character varying, "email" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_237defd1d8996a3d47ea591e1c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."candidate_profiles_visibility_enum" AS ENUM('locked', 'public', 'urgent')`);
        await queryRunner.query(`CREATE TYPE "public"."candidate_profiles_gender_enum" AS ENUM('male', 'female', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."candidate_profiles_marital_status_enum" AS ENUM('single', 'married', 'other')`);
        await queryRunner.query(`CREATE TABLE "candidate_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "full_name" character varying NOT NULL, "desired_position" character varying, "desired_level" character varying, "desired_salary_min" integer, "desired_salary_max" integer, "visibility" "public"."candidate_profiles_visibility_enum" NOT NULL DEFAULT 'public', "completion_percent" integer NOT NULL DEFAULT '0', "allow_job_notifications" boolean NOT NULL DEFAULT true, "profile_title" character varying, "last_name" character varying, "first_name" character varying, "date_of_birth" date, "gender" "public"."candidate_profiles_gender_enum", "phone" character varying, "contact_email" character varying, "nationality" character varying, "marital_status" "public"."candidate_profiles_marital_status_enum", "country" character varying, "province" character varying, "district" character varying, "address" character varying, "avatar_data" bytea, "avatar_mime_type" character varying, "career_objective" text, "desired_industries" text, "desired_locations" text, "desired_job_types" text, "salary_currency" character varying NOT NULL DEFAULT 'VND', "years_of_experience" integer, "current_level" character varying, "highest_degree" character varying, "hide_contact_info" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5a3673f11918bcea56f48549603" UNIQUE ("user_id"), CONSTRAINT "REL_5a3673f11918bcea56f4854960" UNIQUE ("user_id"), CONSTRAINT "PK_8e8cf5b54118601673585218cc4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7d439d2e94c159f1d6d91f7ba1" ON "candidate_profiles"  ("desired_level") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd6014d81960dbfbefd6d9ee6e" ON "candidate_profiles"  ("visibility") `);
        await queryRunner.query(`CREATE INDEX "IDX_e4fd02eb117b3e786431308f69" ON "candidate_profiles"  ("province") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3ddce10eee0ea08e13730e383" ON "candidate_profiles"  ("years_of_experience") `);
        await queryRunner.query(`CREATE INDEX "IDX_41ec45944871941dc76c03c04d" ON "candidate_profiles"  ("highest_degree") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" character varying NOT NULL, "content" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('candidate', 'employer_main', 'employer_sub', 'moderator', 'admin')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'suspended', 'pending')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "full_name" character varying, "phone" character varying, "password_hash" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'candidate', "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "preferred_language" character varying NOT NULL DEFAULT 'vi', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "search_histories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "owner_type" character varying NOT NULL, "owner_id" character varying NOT NULL, "criteria" jsonb, "result_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_55eb6ed37ed8a334b599b3dfe66" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unlocked_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "candidate_profile_id" uuid NOT NULL, "unlocked_by_user_id" uuid NOT NULL, "order_id" uuid, "unlocked_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a663aea541dd12572b43ec31f6d" UNIQUE ("company_id", "candidate_profile_id"), CONSTRAINT "PK_aa2919f970e2bb9ec1369936d38" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "cvs" ADD CONSTRAINT "FK_28559ff992c0cbdeb49255974e3" FOREIGN KEY ("candidate_profile_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_users" ADD CONSTRAINT "FK_0a12e8588834314e38e43d6f5a7" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_users" ADD CONSTRAINT "FK_0363bc7120c6f81b0fdf3a77a8e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b2f7b823a21562eeca20e72b006" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_ea83c3b911906a3578de2340fdf" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_f5d519a61e918f7efb299de31a0" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_8e6b747bc638f155b0a8e365738" FOREIGN KEY ("service_package_id") REFERENCES "service_packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_770f0a8b0033dd04c3fcc55d695" FOREIGN KEY ("job_posting_id") REFERENCES "job_postings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_dc56541877aa49408cdf38a7359" FOREIGN KEY ("cv_id") REFERENCES "cvs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_postings" ADD CONSTRAINT "FK_bd239aea48fdd78095c23e51e0e" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" ADD CONSTRAINT "FK_0ad795b4a468cf434d5b95d7309" FOREIGN KEY ("candidate_profile_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" ADD CONSTRAINT "FK_d9323d330ebb84ee27feb41bec8" FOREIGN KEY ("job_posting_id") REFERENCES "job_postings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blocked_companies" ADD CONSTRAINT "FK_c26d2ba17883d59ffcf6112838f" FOREIGN KEY ("candidate_profile_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blocked_companies" ADD CONSTRAINT "FK_993c7d2e628abfae3de3e8a3f6f" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_experiences" ADD CONSTRAINT "FK_42a0be55d27b8a56dd353d1722f" FOREIGN KEY ("candidate_profile_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_educations" ADD CONSTRAINT "FK_b40491477802c5dcda1dfd4f002" FOREIGN KEY ("candidate_profile_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_certificates" ADD CONSTRAINT "FK_6cee995b4c89f89624b274aeabf" FOREIGN KEY ("candidate_profile_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_languages" ADD CONSTRAINT "FK_164d230e87dd419b4f5d772f1ac" FOREIGN KEY ("candidate_profile_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_skills" ADD CONSTRAINT "FK_80ceccf8e3e4dd72fe3963dbd5a" FOREIGN KEY ("candidate_profile_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_achievements" ADD CONSTRAINT "FK_1ef6548c1c83274b0a2b315a6ed" FOREIGN KEY ("candidate_profile_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_activities" ADD CONSTRAINT "FK_2949111dfc90771b17d4e5d41a0" FOREIGN KEY ("candidate_profile_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_references" ADD CONSTRAINT "FK_9d39ed52cf971dede4cead870cd" FOREIGN KEY ("candidate_profile_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_profiles" ADD CONSTRAINT "FK_5a3673f11918bcea56f48549603" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unlocked_profiles" ADD CONSTRAINT "FK_60a9efb50f96155e6499039004f" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unlocked_profiles" ADD CONSTRAINT "FK_abaf6fc3795381824b7a73f2599" FOREIGN KEY ("candidate_profile_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unlocked_profiles" ADD CONSTRAINT "FK_f2070a94a1a4d3ad8d22009612a" FOREIGN KEY ("unlocked_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unlocked_profiles" ADD CONSTRAINT "FK_62923a67a460d7e9b8ad5126de8" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "unlocked_profiles" DROP CONSTRAINT "FK_62923a67a460d7e9b8ad5126de8"`);
        await queryRunner.query(`ALTER TABLE "unlocked_profiles" DROP CONSTRAINT "FK_f2070a94a1a4d3ad8d22009612a"`);
        await queryRunner.query(`ALTER TABLE "unlocked_profiles" DROP CONSTRAINT "FK_abaf6fc3795381824b7a73f2599"`);
        await queryRunner.query(`ALTER TABLE "unlocked_profiles" DROP CONSTRAINT "FK_60a9efb50f96155e6499039004f"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "candidate_profiles" DROP CONSTRAINT "FK_5a3673f11918bcea56f48549603"`);
        await queryRunner.query(`ALTER TABLE "candidate_references" DROP CONSTRAINT "FK_9d39ed52cf971dede4cead870cd"`);
        await queryRunner.query(`ALTER TABLE "candidate_activities" DROP CONSTRAINT "FK_2949111dfc90771b17d4e5d41a0"`);
        await queryRunner.query(`ALTER TABLE "candidate_achievements" DROP CONSTRAINT "FK_1ef6548c1c83274b0a2b315a6ed"`);
        await queryRunner.query(`ALTER TABLE "candidate_skills" DROP CONSTRAINT "FK_80ceccf8e3e4dd72fe3963dbd5a"`);
        await queryRunner.query(`ALTER TABLE "candidate_languages" DROP CONSTRAINT "FK_164d230e87dd419b4f5d772f1ac"`);
        await queryRunner.query(`ALTER TABLE "candidate_certificates" DROP CONSTRAINT "FK_6cee995b4c89f89624b274aeabf"`);
        await queryRunner.query(`ALTER TABLE "candidate_educations" DROP CONSTRAINT "FK_b40491477802c5dcda1dfd4f002"`);
        await queryRunner.query(`ALTER TABLE "candidate_experiences" DROP CONSTRAINT "FK_42a0be55d27b8a56dd353d1722f"`);
        await queryRunner.query(`ALTER TABLE "blocked_companies" DROP CONSTRAINT "FK_993c7d2e628abfae3de3e8a3f6f"`);
        await queryRunner.query(`ALTER TABLE "blocked_companies" DROP CONSTRAINT "FK_c26d2ba17883d59ffcf6112838f"`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" DROP CONSTRAINT "FK_d9323d330ebb84ee27feb41bec8"`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" DROP CONSTRAINT "FK_0ad795b4a468cf434d5b95d7309"`);
        await queryRunner.query(`ALTER TABLE "job_postings" DROP CONSTRAINT "FK_bd239aea48fdd78095c23e51e0e"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_dc56541877aa49408cdf38a7359"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_770f0a8b0033dd04c3fcc55d695"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_8e6b747bc638f155b0a8e365738"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_f5d519a61e918f7efb299de31a0"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_ea83c3b911906a3578de2340fdf"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b2f7b823a21562eeca20e72b006"`);
        await queryRunner.query(`ALTER TABLE "company_users" DROP CONSTRAINT "FK_0363bc7120c6f81b0fdf3a77a8e"`);
        await queryRunner.query(`ALTER TABLE "company_users" DROP CONSTRAINT "FK_0a12e8588834314e38e43d6f5a7"`);
        await queryRunner.query(`ALTER TABLE "cvs" DROP CONSTRAINT "FK_28559ff992c0cbdeb49255974e3"`);
        await queryRunner.query(`DROP TABLE "unlocked_profiles"`);
        await queryRunner.query(`DROP TABLE "search_histories"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41ec45944871941dc76c03c04d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3ddce10eee0ea08e13730e383"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4fd02eb117b3e786431308f69"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd6014d81960dbfbefd6d9ee6e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d439d2e94c159f1d6d91f7ba1"`);
        await queryRunner.query(`DROP TABLE "candidate_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."candidate_profiles_marital_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."candidate_profiles_gender_enum"`);
        await queryRunner.query(`DROP TYPE "public"."candidate_profiles_visibility_enum"`);
        await queryRunner.query(`DROP TABLE "candidate_references"`);
        await queryRunner.query(`DROP TABLE "candidate_activities"`);
        await queryRunner.query(`DROP TABLE "candidate_achievements"`);
        await queryRunner.query(`DROP TABLE "candidate_skills"`);
        await queryRunner.query(`DROP TYPE "public"."candidate_skills_level_enum"`);
        await queryRunner.query(`DROP TABLE "candidate_languages"`);
        await queryRunner.query(`DROP TYPE "public"."candidate_languages_level_enum"`);
        await queryRunner.query(`DROP TABLE "candidate_certificates"`);
        await queryRunner.query(`DROP TABLE "candidate_educations"`);
        await queryRunner.query(`DROP TABLE "candidate_experiences"`);
        await queryRunner.query(`DROP TABLE "blocked_companies"`);
        await queryRunner.query(`DROP TABLE "saved_jobs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5985a72c87165933e440392de3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68887787f572d94640efb1e595"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f82c7b577f57dd7c3ef5f79f08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3adbc559e344968a1d216d9798"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b11b4640f95bb56b6bd3c2c04f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1a959e31fc12e2fc21542e6c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_580ae81cb102623fd17eb424ac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c7584f5c38d2693d38c076cea5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd239aea48fdd78095c23e51e0"`);
        await queryRunner.query(`DROP TABLE "job_postings"`);
        await queryRunner.query(`DROP TYPE "public"."job_postings_approval_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae4173257eebabee3db1cee885"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d134cbc7a07bded22846799771"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b9836f9e3cd74cfcb2c2da66d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2b6efa58d11141449bc3a12de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ee114cee92e995a9e75c05cfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc56541877aa49408cdf38a735"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_770f0a8b0033dd04c3fcc55d69"`);
        await queryRunner.query(`DROP TABLE "applications"`);
        await queryRunner.query(`DROP TYPE "public"."applications_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2eb06ff133d04a6805a3fa4cea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b955c977390fc5903ea2519506"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`DROP TYPE "public"."companies_approval_status_enum"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_payment_method_enum"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TABLE "service_packages"`);
        await queryRunner.query(`DROP TABLE "company_users"`);
        await queryRunner.query(`DROP TYPE "public"."company_users_type_enum"`);
        await queryRunner.query(`DROP TABLE "cvs"`);
        await queryRunner.query(`DROP TYPE "public"."cvs_type_enum"`);
    }

}
