import 'dotenv/config';
import { DataSource } from 'typeorm';
import {
  User,
  CandidateProfile,
  CV,
  Company,
  CompanyUser,
  JobPosting,
  Application,
  ApplicationStatusHistory,
  SavedJob,
  BlockedCompany,
  SearchHistory,
  ServicePackage,
  Order,
  Payment,
  Invoice,
  Notification,
  CandidateExperience,
  CandidateEducation,
  CandidateCertificate,
  CandidateLanguage,
  CandidateSkill,
  CandidateAchievement,
  CandidateActivity,
  CandidateReference,
  UnlockedProfile,
  AdminAuditLog,
} from './entities';

// Đợt 12a (20/09/2026) — DataSource riêng cho TypeORM CLI (migration:generate/run/revert), tách
// khỏi TypeOrmModule.forRootAsync() ở app.module.ts (dùng cho lúc chạy app thật qua NestJS DI).
// synchronize LUÔN false ở đây — CLI chỉ dùng để tạo/chạy migration, không bao giờ tự đồng bộ.
export const AppDataSource = new DataSource({
  type: 'postgres',
  url: process.env.DATABASE_URL,
  entities: [
    User,
    CandidateProfile,
    CV,
    Company,
    CompanyUser,
    JobPosting,
    Application,
    ApplicationStatusHistory,
    SavedJob,
    BlockedCompany,
    SearchHistory,
    ServicePackage,
    Order,
    Payment,
    Invoice,
    Notification,
    CandidateExperience,
    CandidateEducation,
    CandidateCertificate,
    CandidateLanguage,
    CandidateSkill,
    CandidateAchievement,
    CandidateActivity,
    CandidateReference,
    UnlockedProfile,
    AdminAuditLog,
  ],
  migrations: [__dirname + '/migrations/*.{ts,js}'],
  synchronize: false,
  logging: false,
  ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: false } : false,
});
