import 'dotenv/config';
import { JobReport } from './entities/job-report.entity';
import { DataSource } from 'typeorm';
import {
  User,
  CandidateProfile,
  CV,
  Company,
  CompanyUser,
  JobPosting,
  Application,
  ApplicationStatusHistory,
  SavedJob,
  BlockedCompany,
  SearchHistory,
  ServicePackage,
  Order,
  Payment,
  Invoice,
  Notification,
  CandidateExperience,
  CandidateEducation,
  CandidateCertificate,
  CandidateLanguage,
  CandidateSkill,
  CandidateAchievement,
  CandidateActivity,
  CandidateReference,
  UnlockedProfile,
  AdminAuditLog,
  CompanyFollow,
  CandidateNote,
  WorkLocation,
  AdminSetting,
  CompanyClaimRequest,
  CvArchiveCandidate,
  CvArchiveEntry,
  CandidateProfileRequest,
  AdminCandidateNote,
  AnalyticsSession,
  AnalyticsPageview,
  AnalyticsEvent,
  AnalyticsDaily,
  AnalyticsBotHit,
  StoredFile,
  AdCampaign,
  AdCampaignStat,
  BgImage,
} from './entities';

// Đợt 12a (20/09/2026) — DataSource riêng cho TypeORM CLI (migration:generate/run/revert), tách
// khỏi TypeOrmModule.forRootAsync() ở app.module.ts (dùng cho lúc chạy app thật qua NestJS DI).
// synchronize LUÔN false ở đây — CLI chỉ dùng để tạo/chạy migration, không bao giờ tự đồng bộ.
export const AppDataSource = new DataSource({
  type: 'postgres',
  url: process.env.DATABASE_URL,
  entities: [
    User,
    CandidateProfile,
    CV,
    Company,
    CompanyUser,
    JobPosting,
    Application,
    ApplicationStatusHistory,
    SavedJob,
    BlockedCompany,
    SearchHistory,
    ServicePackage,
    Order,
    Payment,
    Invoice,
    Notification,
    CandidateExperience,
    CandidateEducation,
    CandidateCertificate,
    CandidateLanguage,
    CandidateSkill,
    CandidateAchievement,
    CandidateActivity,
    CandidateReference,
    UnlockedProfile,
    AdminAuditLog,
    CompanyFollow,
    CandidateNote,
    WorkLocation,
    AdminSetting,
    // Đợt 18a — bổ sung CompanyClaimRequest (Đợt 17 quên khai báo ở đây, chỉ ảnh hưởng lệnh
    // migration:generate, không ảnh hưởng migration:run) + 2 bảng Kho CV.
    CompanyClaimRequest,
    CvArchiveCandidate,
    CvArchiveEntry,
    CandidateProfileRequest,
    AdminCandidateNote,
    // Đợt 19 — phân tích truy cập thật.
    AnalyticsSession,
    AnalyticsPageview,
    AnalyticsEvent,
    AnalyticsDaily,
    AnalyticsBotHit,
    // Đợt 20 — sổ theo dõi file trên Google Drive.
    StoredFile,
    AdCampaign,
    AdCampaignStat,
    BgImage,
    JobReport,
  ],
  migrations: [__dirname + '/migrations/*.{ts,js}'],
  synchronize: false,
  logging: false,
  ssl:
    process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: false } : false,
});
